
==================[22.10.2020 00:54:57]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 192.168.8.133:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:54:58]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:54:58]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:54:58]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:54:58]==================
System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
=========================================================

==================[22.10.2020 00:54:58]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:54:58]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:54:58]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
=========================================================

==================[22.10.2020 00:54:58]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
=========================================================

==================[22.10.2020 00:54:58]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
=========================================================

==================[22.10.2020 00:54:58]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at void MySql.Data.MySqlClient.MySqlConnection.Open()
=========================================================

==================[22.10.2020 00:54:58]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.17
==================[22.10.2020 00:55:52]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 192.168.8.133:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:55:53]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:55:53]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:55:53]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:55:53]==================
System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
=========================================================

==================[22.10.2020 00:55:53]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:55:53]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:55:53]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
=========================================================

==================[22.10.2020 00:55:53]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
=========================================================

==================[22.10.2020 00:55:53]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
=========================================================

==================[22.10.2020 00:55:53]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at void MySql.Data.MySqlClient.MySqlConnection.Open()
=========================================================

==================[22.10.2020 00:55:53]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.17
==================[22.10.2020 00:56:12]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 192.168.8.133:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:56:13]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:56:13]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:56:13]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:56:13]==================
System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
=========================================================

==================[22.10.2020 00:56:13]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:56:13]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:56:13]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
=========================================================

==================[22.10.2020 00:56:13]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
=========================================================

==================[22.10.2020 00:56:13]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tas
==================[22.10.2020 00:56:55]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 192.168.8.133:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:56:56]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:56:56]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:56:56]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:56:56]==================
System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
=========================================================

==================[22.10.2020 00:56:56]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:56:56]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:56:56]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
=========================================================

==================[22.10.2020 00:56:56]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
=========================================================

==================[22.10.2020 00:56:56]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
=========================================================

==================[22.10.2020 00:56:56]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at void MySql.Data.MySqlClient.MySqlConnection.Open()
=========================================================

==================[22.10.2020 00:56:56]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.17
==================[22.10.2020 00:57:09]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 192.168.8.133:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:57:10]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:57:10]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:57:10]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[22.10.2020 00:57:10]==================
System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
=========================================================

==================[22.10.2020 00:57:10]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:57:10]==================
System.IO.FileNotFoundException: Could not load file or assembly 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'. The system cannot find the file specified.
File name: 'E:\Games\RageServer\server-files\dotnet\resources\lrp\lrp\bin\Debug\netcoreapp2.0\MySql.Data.resources.dll'
   at void System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, string ilPath, string niPath, ObjectHandleOnStack retAssembly)


=========================================================

==================[22.10.2020 00:57:10]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
=========================================================

==================[22.10.2020 00:57:10]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
=========================================================

==================[22.10.2020 00:57:10]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
=========================================================

==================[22.10.2020 00:57:10]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.177:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at Task System.Net.Sockets.TcpClient.ConnectAsync(string host, int port)+(IAsyncResult asyncResult) => { } [1]
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at void System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at Stream MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at void MySql.Data.MySqlClient.MySqlConnection.Open()
=========================================================

==================[22.10.2020 00:57:10]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 169.254.126.177:3306)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 169.254.126.17